services:
    pgadmin4:
      # Offical image from https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
      image: dpage/pgadmin4:8
      container_name: pgadmin
      ports:
       - 8080:80
      environment:
       - PGADMIN_DEFAULT_EMAIL=student@thi.de
       - PGADMIN_DEFAULT_PASSWORD=123456789#

    postgres:
      # Official Image from https://hub.docker.com/_/postgres
      image: postgres:16-alpine
      container_name: dbs-postgres
      ports:
        - 5432:5432
      environment:
       - POSTGRES_USER=student
       - POSTGRES_PASSWORD=123456789#
       - POSTGRES_DB=example
      volumes:
       - postgres-data:/var/lib/postgresql/data

volumes:
  pgadmin-config:
  postgres-data: